version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: babaorum/docker-and-compose:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          mkdir vendor
          docker build -f docker/php/Dockerfile .
