services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shippeo\Heimdall\:
        resource: '../../../../../*'

    Shippeo\Heimdall\Application\AddMetric:
        arguments:
            - !tagged monitoring.database
        public: true
